name: 'Publish NPM Package'

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:

permissions:
  contents: 'read'

jobs:
  read-versions:
    runs-on: 'ubuntu-latest'
    outputs:
      # pnpm version specified in package.json$.packageManager
      pnpm: '${{ steps.read-versions.outputs.pnpm }}'
    steps:
      - name: 'Checkout Repository ğŸ›ï¸'
        uses: 'actions/checkout@v4'
      - name: 'read versions ğŸ”–'
        id: 'read-versions'
        run: |
          set -e
          echo "pnpm=$(jq --raw-output '.packageManager | split("@")[1]' package.json)" >> "$GITHUB_OUTPUT"

  build:
    runs-on: 'ubuntu-latest'
    needs:
      - 'read-versions'
    steps:
      # - name: 'Setup node ğŸ›ï¸'
      #   uses: 'dudeofawesome/actions/node-setup@a850bdff4354bdb891a86116f0378f8a890e2c16' # v1
      - name: 'Checkout Repository ğŸ›ï¸'
        uses: 'actions/checkout@v4'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '${{ needs.read-versions.outputs.pnpm }}'
      - name: 'Use Node.js ğŸ“—'
        uses: 'actions/setup-node@v4'
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: 'Install node modules ğŸ“¥'
        run: 'pnpm install --frozen-lockfile'
      - name: 'Build ğŸ—ï¸'
        run: 'pnpm run build'

  lint:
    runs-on: 'ubuntu-latest'
    needs:
      - 'read-versions'
    steps:
      # - name: 'Setup node ğŸ›ï¸'
      #   uses: 'dudeofawesome/actions/node-setup@a850bdff4354bdb891a86116f0378f8a890e2c16' # v1
      - name: 'Checkout Repository ğŸ›ï¸'
        uses: 'actions/checkout@v4'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '${{ needs.read-versions.outputs.pnpm }}'
      - name: 'Use Node.js ğŸ“—'
        uses: 'actions/setup-node@v4'
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: 'Install node modules ğŸ“¥'
        run: 'pnpm install --frozen-lockfile'
      - name: 'Build ğŸ—ï¸'
        run: 'pnpm run build'
      - name: 'Lint ğŸ§ª'
        run: 'pnpm run lint'

  test:
    runs-on: 'ubuntu-latest'
    needs:
      - 'read-versions'
    steps:
      # - name: 'Setup node ğŸ›ï¸'
      #   uses: 'dudeofawesome/actions/node-setup@a850bdff4354bdb891a86116f0378f8a890e2c16' # v1
      - name: 'Checkout Repository ğŸ›ï¸'
        uses: 'actions/checkout@v4'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '${{ needs.read-versions.outputs.pnpm }}'
      - name: 'Use Node.js ğŸ“—'
        uses: 'actions/setup-node@v4'
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: 'Install node modules ğŸ“¥'
        run: 'pnpm install --frozen-lockfile'
      - name: 'Build ğŸ—ï¸'
        run: 'pnpm run build'
      - name: 'Test ğŸ§ª'
        run: 'pnpm run test'

  publish:
    runs-on: 'ubuntu-latest'
    environment: 'production'
    permissions:
      id-token: 'write'
      packages: 'write'
      contents: 'write'
    needs:
      - 'read-versions'
      - 'build'
      - 'lint'
      - 'test'
    steps:
      # - name: 'Setup node ğŸ›ï¸'
      #   uses: 'dudeofawesome/actions/node-setup@a850bdff4354bdb891a86116f0378f8a890e2c16' # v1
      #   with:
      #     install-modules: false
      - name: 'Checkout Repository ğŸ›ï¸'
        uses: 'actions/checkout@v4'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '${{ needs.read-versions.outputs.pnpm }}'
      - name: 'Use Node.js ğŸ“—'
        uses: 'actions/setup-node@v4'
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: 'Install node modules ğŸ“¥'
        run: 'pnpm install --frozen-lockfile'

      - name: 'Login to npm ğŸ”'
        run: |
          npm set "//registry.npmjs.org/:_authToken" "${{ secrets.NPM_AUTH_TOKEN }}"
      - name: 'Publish to npm ğŸš€'
        # env:
        #   NODE_AUTH_TOKEN: '${{ secrets.NPM_AUTH_TOKEN }}'
        # uses: 'dudeofawesome/actions/npm-publish@a850bdff4354bdb891a86116f0378f8a890e2c16' # v1
        run: 'pnpm publish'
